---
title: "IN2332 Case Study"
author: "Derrick Lim Tze Hsien"
date: "June 20, 2017"
output: html_document
---

```{r setup, include=FALSE}
tab = read.csv("more_football.csv")
# make new column 'day', which numbers the match days accross seasons
tab$day = as.integer(factor(with(tab, paste(season, sprintf("%02d", matchday), sep="_"))))
# we focus on predicting the outcome: win, draw, or lose
tab$outcome = with(tab, ifelse(homegoals>guestgoals, "win", ifelse(homegoals==guestgoals, "draw", "lose")))
head(tab)
set.seed(42)
```

```{r}
minday = max(tab$day) - 50
# Naive prediction of win, draw, lose probabilities from simple fractions of all
# games the HOME team played INDEPENDENT of the opponent
predictNaiveProbs <- function (pred_match, data) {
  data$home = factor(data$home)
  probs = sapply(
    1:nrow(pred_match),
    function(i){
      x1 = as.character(pred_match[i,1]) #home team
      x2 = as.character(pred_match[i,2]) #guest team
      ## for a match with a new team, equal probs of outcomes
      ## (feel free to make this more clever)
      if(!(x1 %in% levels(data$home))) {
        if(!(x2 %in% levels(data$guest))) {
          return (c(win=1/3, draw=1/3, lose=1/3))
        }
        return (c(win=0, draw=0, lose=1))
      } else {
        if(!(x2 %in% levels(data$guest))) {
          return (c(win=1, draw=0, lose=0))
        }
      }
      rh_x1_home = data$outcome[data$home==x1]
      rh_x1_guest = data$outcome[data$guest==x1]
      
      rh_x2_home = data$outcome[data$home==x2]
      rh_x2_guest = data$outcome[data$guest==x2]
      
      x1_vs_x2 = data$outcome[data$home==x1 & data$guest==x2]
      
      #print(paste(x1," vs ",x2," ",result_history))
      w1 = 0.275
      w2 = 0.175
      w3 = 0.075
      w4 = 0.175
      w5 = 0.3
      return( c(
        win = w1*mean(rh_x1_home == "win")+w2*mean(rh_x1_guest=="win")+w3*mean(rh_x2_home=="win")+w4*mean(rh_x2_guest=="win")+w5*mean(x1_vs_x2=="win"),
        draw = w1*mean(rh_x1_home == "draw")+w2*mean(rh_x1_guest=="draw")+w3*mean(rh_x2_home=="draw")+w4*mean(rh_x2_guest=="draw")+w5*mean(x1_vs_x2=="draw"),
        lose = w1*mean(rh_x1_home == "lose")+w2*mean(rh_x1_guest=="lose")+w3*mean(rh_x2_home=="lose")+w4*mean(rh_x2_guest=="lose")+w5*mean(x1_vs_x2=="lose")
      ))
    }
  )
  t(probs)
}
# predictions of next day match from minday to last day before the match
outcomeConfidence = function(minday, tab){
  probs = as.data.frame(matrix(NA, nrow=nrow(tab), ncol=3))
  for(d in minday:max(tab$day)){
    tab_past = subset(tab, day<d)
    pred_row = which(tab$day==d)
    pred_match = tab[pred_row, c("home", "guest"), drop=FALSE]
    probs[pred_row, ] = predictNaiveProbs(pred_match, tab_past)
  }
  colnames(probs) = c("win", "draw", "lose")
  data.frame(
  pred_outcome = colnames(probs) [apply(probs, 1, function(x) if(any(is.na(x))) {NA} else {which.max(x)})],
  pred_confidence = apply(probs, 1, max))
}
```

```{r}
# predictions and confidence scores for the games
# The output is a data.frame of same rowlength as the original data
# But with NAs for those games, which were not predicted
oc = outcomeConfidence(minday, tab)
# bind prediction data.frame to the original data
fulltab = cbind(tab, oc)
head(fulltab)
# number of correct predictions: this is the value to perform best on
sum(fulltab$pred_outcome==fulltab$outcome, na.rm=TRUE)
# getting more insights: confusion table (only for those over 50% probability)
table(outcome = fulltab$outcome[fulltab$pred_confidence>0.5], pred = fulltab$pred_outcome[fulltab$pred_confidence>0.5])
table(outcome = fulltab$outcome[!is.na(fulltab$pred_confidence)],
pred = fulltab$pred_outcome[!is.na(fulltab$pred_confidence)])
# getting more insights: true positive rate vs ranked predictions
getTPR = function(oc, tab){
  oc$tp = tab$outcome == oc$pred_outcome
  oco = oc[order(oc$pred_confidence, decreasing=TRUE), ]
  oco$tpr = cumsum(oco$tp)/1:nrow(oco)
  oco
}
oco = getTPR (oc, tab)
plot(na.omit(oco$tpr), ylim=c(0,1), type="l", xlab="prediction ranked by decreasing confidence score", ylab="true positive rate")
```

```{r}
# get random results for comparison
fulltab$random = NA
idx = which(!is.na(fulltab$pred_confidence))
fulltab$random[idx] = sample(c("win", "draw", "lose"), length(idx), replace = TRUE)
sum(fulltab$random==fulltab$outcome, na.rm=TRUE)
table(outcome = fulltab$outcome[!is.na(fulltab$pred_confidence)],
pred = fulltab$random[!is.na(fulltab$pred_confidence)])
```

```{r}
# applying a rejection threshold, e.g. if confidence is below 0.6 we just randomly select an outcome
idx = which(fulltab$pred_confidence < 0.6)
fulltab$adj_outcome = fulltab$pred_outcome
fulltab$adj_outcome[idx] = sample(c("win", "draw", "lose"), length(idx), replace = TRUE)
sum(fulltab$adj_outcome==fulltab$outcome, na.rm=TRUE)
table(outcome = fulltab$outcome[!is.na(fulltab$pred_confidence)],
pred = fulltab$adj_outcome[!is.na(fulltab$pred_confidence)])
```
